SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int = 720
FPS: int = 60
SHIP_COLOR: str = "yellow"
ASTEROID_COLOR: str = "white"
MIN_SPAWN_DISTANCE: int = 100  # in pixels, prevent spawn-deaths
GAME_CAPTION: str = "PyGons!"
DEVELOPER_NAME: str = "Alejandro Alvarado"
DEVELOPER_DISCORD: str = "alejandroa1217"
DEVELOPER_GITHUB: str = "alejaalvar"
SHOOT_COOLDOWN: float = 0.3
